services:
  lab1:
    build:
      context: ./lab1
    container_name: lab1
    working_dir: /app
    volumes:
      - ./lab1:/app
    stdin_open: true
    tty: true
    command: python main.py

  lab2:
    build:
      context: ./lab2
    container_name: lab2
    working_dir: /app
    volumes:
      - ./lab2:/app
      - ./lab2/data:/app/data
      - ./lab2/output:/app/output
    command: python main.py

  lab3:
    build:
      context: ./lab3
    container_name: lab3
    working_dir: /app
    volumes:
      - ./lab3:/app
      - ./lab3/data:/app/data
      - ./lab3/output:/app/output
    command: python main.py

  lab4:
    build:
      context: ./lab4
    container_name: lab4
    working_dir: /app
    volumes:
      - ./lab4:/app  
      - ./lab4/data:/app/data 
      - ./lab4/output:/app/output
    stdin_open: true
    tty: true
    command: python main.py

  lab5:
    build:
      context: ./lab5
    container_name: lab5
    working_dir: /app
    volumes:
      - ./lab5:/app  
      - ./lab5/data:/app/data 
      - ./lab5/output:/app/output
    stdin_open: true
    tty: true
    command: python main.py
