name: Lab 5 CI

on:
  push:
    branches: [ "feature/05-tkinter-gui" ] 
    paths: 
      - 'lab5/**'
      - 'docker-compose.yml' 
      - '.github/workflows/lab5-ci.yml' 

permissions:
  contents: read

jobs:
  test-lab5: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Lab 5 Docker image
      uses: docker compose build lab5

    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v3 
