name: Lab 6 CI

on:
  push:
    branches: [ "feature/06-plagiarism-check" ]
    paths:
      - 'lab6/**'
      - '.github/workflows/lab6-ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'lab6/**'
      - '.github/workflows/lab6-ci.yml'

permissions:
  contents: read

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: docker_build
        run: |
          docker build \
            --tag lab6-image:latest \
            --file ./lab6/Dockerfile \
            ./lab6
          echo "Image built successfully: lab6-image:latest"

  test:
    name: Run Pytest Tests
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Run tests using Docker Compose
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          echo "Creating dummy .env file for Docker Compose..."
          mkdir -p ./lab6
          touch ./lab6/.env
          echo "Running tests within the container..."
          docker compose run --rm -e GOOGLE_API_KEY=$GOOGLE_API_KEY lab6 pytest tests/