name: Lab 6 CI

on:
  push:
    branches: [ "feature/06-plagiarism-check" ]
    paths:
      - 'lab6/**'
      - '.github/workflows/lab6-ci.yml'

permissions:
  contents: read 

jobs:
  build-lab6: 
    name: Build Lab 6 Docker Image 
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image for Lab 6
      run: |
        docker build \
          --tag lab6-image:latest \
          --file ./lab6/Dockerfile \
          ./lab6
